config/routes.rb
Myrottenpotatoes::Application.routes.draw do

  devise_for :users do
  get "/users/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  #get "/users/edit" => "devise/registration#edit", :as => :edit_profile
  end
  #devise_for :users, :controllers => { registrations: 'registrations' }
  #devise_for :users, :controllers => { :sessions => "users/sessions" }
  resources :events
  resources :users
  get '/eventspage' => 'events#eventspage'
  get '/homepage' => 'events#homepage'
  root 'events#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
    devise :database_authenticatable, :lockable, :recoverable, :rememberable, :trackable
end

app/models/car_owner.rb
class CarOwner < ActiveRecord::Base
    belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :users
end

app/models/movie.rb
class Movie <ActiveRecord::Base
end

app/models/tblwaitlist.rb
class Tblwaitlist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :middle_name, :last_name,
    :date_of_birth, :postal_address, :city, :state, :zip,
    :phone_number, :username, :email, :password, :provider, :uid) }
    
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :middle_name, :last_name,
    :date_of_birth, :postal_address, :city, :state, :zip,
    :phone_number, :username, :email, :password, :provider, :uid) }
  end
  
  protect_from_forgery with: :null_session

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def eventspage
      #@events = Event.where("EventDate between date('now') and date('now' -365)")
        @events = Event.where("EventDate >= DATE('now', 'weekday 0', '-180 days')")
        @events = Event.paginate(page: params[:page], per_page: 5)
    end
    
    def CarryAmount
        @events = Event.where("QuantityCanCarry >= 1)")
    end
    
    
    def find
        @event = Event.new
    end
    
    def new
        @event = current_user.events.build
    end
    
    def edit
      @event = Event.find params[:id]
    end

    
    def show
        id = params[:id] 
        @event = Event.find(id)
    end    
  
    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to eventspage_path
        else
            render 'new'
        end
    end
    
    def edit
      @event = Event.find params[:id]
    end
    
    def update
      @event = Event.find params[:id]
      @event.update_attributes!(event_params)
      redirect_to eventspage_path(@Event)
    end
    
    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to eventspage_path
    end
  
private
    def event_params
        params.require(:event).permit(:EventDate, :EventLocationGPS, :EventLocationFriendly, :ToLocation, :FromLocation, :QuantityCanCarry, :OneWayTrip, :EventBufferTime, :EventComments)
    end
end

app/controllers/movies_controller.rb
# This file is app/controllers/movies_controller.rb
class MoviesController < ApplicationController

rescue_from ::ActiveRecord::RecordNotFound, with: :record_not_found
def record_not_found(exception)
  #render json: {error: exception.message}.to_json, status: 404
   redirect_to movies_path(1)
    return
end

  
def index
    @movies = Movie.all
end


  
def cancel
    @movies = Movie.all
end
  
  
def create
    params.require(:movie)
    my_movie = params[:movie].permit(:title,:rating,:release_date)
    # shortcut: params.require(:movie).permit(:title,:rating,:release_date)
    # rest of code...
    @movie = Movie.create!(my_movie)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
    
end


def set_movie
params[:movie].permit(:title,:rating,:release_date)
end


# in app/controllers/movies_controller.rb
def show
  id = params[:id] # retrieve movie ID from URI route
  @movie = Movie.find(id) # look up movie by unique ID
  # will render app/views/movies/show.html.haml by default
end

def new
  @movie = Movie.new
  # default: render 'new' template
end 


def edit
  @movie = Movie.find params[:id]
end

def update
  @movie = Movie.find params[:id]
  @movie.update_attributes!(set_movie)
  flash[:notice] = "#{@movie.title} was successfully updated."
  redirect_to movie_path
end



end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
private

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
    params.require(:user).permit(:first_name, :middle_name, :last_name,
    :date_of_birth, :postal_address, :city, :state, :zip,
    :phone_number, :username, :provider, :uid, :email, :password, :password_confirmation , :role)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :middle_name, :last_name,
    :date_of_birth, :postal_address, :city, :state, :zip,
    :phone_number, :username, :provider, :uid, :email, :password, :password_confirmation, :current_password , :role , :name)
  end
  
  

end

app/controllers/tblwaitlists_controller.rb
class TblwaitlistsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_events = @user.events.paginate(page: params[:page], per_page: 5)
     current_user
    return
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.email, class: "img-circle")
    end
    
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
    
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tblwaitlist_helper.rb
module TblwaitlistHelper
end

app/helpers/tblwaitlists_helper.rb
module TblwaitlistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.haml
.fieldset
  = simple_form_for(Event.new) do |f|
    = f.input :EventName, label: "Event Name"
    = f.input :EventDate, label: "Event Date"
    = f.input :EventLocationGPS, label: "GPS"      
    = f.input :EventLocationFriendly,   label: "----"
    = f.input :FromLocation,  label: "Starting point"
    = f.input :ToLocation,    label: "Destination"
    = f.input :QuantityCanCarry,  label: "Capacity"
    = f.input :EventBufferTime, label: "Duration"
    = f.input :EventComments, label: "Comment"
    = f.button :submit
   
        

app/views/events/edit.html.haml
%h2 Edit Event Details

= form_tag event_path(@event), :method => :put do

  = label :event, :EventDate, 'Date'
  = date_select :Event, :EventDate
  %br/
  = label :event, :Location, 'Location'
  = text_field :Event, 'Location'
  %br/
  = label :event, :FromLocation, 'Meeting Point'
  = text_field :Event, 'Meeting Point'
  %br/
  = label :event, :ToLocation, 'Destination'
  = text_field :Event, 'Destination'
  %br/
  = label :event, :QuantityCanCarry, 'Can hold'
  = text_field :Event, 'Can hold'
  %br/
  = label :event, :OneWayTrip, 'One way?'
  = text_field :Event, 'One way?'
  %br/
  = label :event, :EventBufferTime, 'Get here by'
  = text_field :Event, 'Get here by'
  %br/
  = label :event, :EventComments, 'Comments'
  = text_field :Event, 'Comments'
  %br/
  = submit_tag 'Save Changes'
  
  = link_to 'Cancel', event_path(@event)

app/views/events/eventspage.html.haml
%h1 Events
%div{:align => "center"}
  = will_paginate
%table#events 
  %thead.tablehead 
    %tr   
      %th ID# 
      %th Date
      %th GPS
      %th Location
      %th Meeting Point 
      %th Destination
      %th Can hold
      %th One way?
      %th Get here by
      %th Comments
      %th More Details
  %tbody
  -@events.each do |event|
    %tr.tablebody
      %td= event.id
      %td= event.EventDate
      %td= event.EventLocationGPS
      %td= event.EventLocationFriendly
      %td= event.FromLocation
      %td= event.ToLocation
      %td= event.QuantityCanCarry
      %td= event.OneWayTrip
      %td= event.EventBufferTime
      %td= event.EventComments
      %td= link_to "Details : #{event.id}", event_path(event)
      
%AddSection
= link_to 'New Event', new_event_path

%div{:align => "center"}
  = will_paginate

app/views/events/homepage.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %link{:href => "http://www.w3schools.com/lib/w3.css", :rel => "stylesheet"}/
    //%link{:href => "app/assets/stylesheets/mycss.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag 'rails'
    :css
      .mySlides {
          display: none;
          border-left: 6px solid red;
          background-color: lightgrey;
          text-indent: 50px;
      }
      #footer {
          clear: both;
          position: fixed;
          background: black;
          color: white;
          bottom: 0;
          left: 0;
          width: 100%;
          height: auto; /* Height of the footer */
          text-align: center;
      }
  %body
  %br/
  %br/
  %center
    %h1.w3-center Ride Me !!!
    .w3-content.w3-section{:style => "max-width:80%;"}
      .mySlides
        %header.w3-container.w3-blue
          %h1 Description :
        %p
          Ride Me is a MSU students project for Software ingeering. The main idea behind this is how to reduce the amount of cars that are going to the same event by using a common car.
          This look like Uber but on a free way and should help people to meet new people and to get along with them on a road trip. What better than a road trip to make new friends?
      .mySlides
        %header.w3-container.w3-blue
          %h1 How to use ?
        %p
          Ride Me is easy to use. First sign up by clicking
          %b sign up
          on the top. Provide the informations that have been asked and the sign up is free. You will be redirect to the coming
          event as soon as you get signed in. By clicking on the specific event you can now join the event and get more info about it. Have fun :)
      .mySlides
        %header.w3-container.w3-blue
          %h1 Contacts :
        %p{:style => "text-align : left;"}
          %img{:src =>  asset_path("kokou.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          Kokou Kingbede : kokou.kingbede@mnsu.edu
        %p{:style => "text-align : left;"}
          %img{:src =>  asset_path("niraj.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          Niraj Gupta : gupta.niraz@gmail.com
        %p{:style => "text-align : left;"}
          %img{:src =>  asset_path("nafi.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          Nafi Nafuil Karim : nafiul-karim.nafi@mnsu.edu
        %p{:style => "text-align : left;"}
          %img{:src =>  asset_path("car2.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          Barry : barryj217@yahoo.com
      .mySlides
        %header.w3-container.w3-blue
          %h1 Snapshots :
          %img{:src =>  asset_path("car3.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("car2.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("girl.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("thank.png"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("thankride.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("thank2.jpg"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("img1.JPG"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("img2.JPG"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("img3.JPG"), :width => "15%",:height => "5%", :float => "right"}/
          %img{:src =>  asset_path("img4.JPG"), :width => "15%",:height => "5%", :float => "right"}/
      .mySlides
        %header.w3-container.w3-blue
          %h1 Contributors :
        %p
          %b{:style => "color: white; background-color: #4286f4;"} Kokou Kingbede (Software Engineer ,Master in Computer Science, Programming and Networking):
        %p Project Manager; Enthousiastic he push everyone to work as their best. He come up with the output and views(Html, Javascript...)
        %p
          %b{:style => "color: white; background-color: #4286f4;"} Niraj Gupta (IT consultant , Master in Computer Science, Programing and Software testing):
        %p Work on the ruby rails coding, Controller and models...
        %p
          %b{:style => "color: white; background-color: #4286f4;"} Nafi Nafuil Karim (IT consultant , Bachelor in Computer Science, Programing and Software testing):
        %p Work on the ruby rails coding too, Controller and models...
        %p
          %b{:style => "color: white; background-color: #4286f4;"} Barry(Master in Computer Science, Programing and Software testing, Actual Engineer at GGG) :
        %p Create the database model and the CSS...
        %p
          Special Thanks to
          %b Dr. Jonathan C. Hardwick
          for his special advices and lessons during the accomplishment of this.
  %a.w3-btn-floating.w3-display-left{:onclick => "plusDivs(-1)"} ❮
  %a.w3-btn-floating.w3-display-right{:onclick => "plusDivs(1)"} ❯
  :javascript
    var myIndex = 0;
    carousel();
    var myIndex = 0;
      carousel();
      var slideIndex = 1;
      showDivs(slideIndex);

      function plusDivs(n) {
          showDivs(slideIndex += n);
      }

      function showDivs(n) {
          var i;
          var x = document.getElementsByClassName("mySlides");
          if (n > x.length) { slideIndex = 1 }
          if (n < 1) { slideIndex = x.length }
          for (i = 0; i < x.length; i++) {
              x[i].style.display = "none";
          }
          x[slideIndex - 1].style.display = "block";
      }

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(carousel, 9000); // Change image every 10 seconds
    }
    function carOwner() {
        alert($('#carOwnerSelect').val());
        if ($('#carOwnerSelect').val() == "Y") {
            $('#not_A_car_owner').hide();
            $('#Car_owner').show();
        } else {
            $('#not_A_car_owner').show();
            $('#Car_owner').hide();
        }
    }

app/views/events/index.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
%table
  %tbody
    %tr
      %td 
      %img{:height => "400", :src => asset_path("mpls_orig.jpg"), :width => "600", :float=>"right"}
      %td 
      %h2 Life's a Journey, enjoy the Ride
    %tr
      %td 
      %h3 RideMe! is a fun, free ride-share app that connects drivers, with those seeking a ride.
      %br
      %h6 Niraj Gupta     |     Kokou Kingbede     |     Nafiul Karim Nafi     |     John Rollins
      %td 
      %h6 Copyright 2016

app/views/events/new.html.haml
%h1 Events
%p
= form_for(Event.new) do
  = label :event, :EventDate, 'Date'
  = date_field :event, :EventDate
  %br/
  = label :event, :EventLocationGPS, 'GPS'
  = text_field :event, 'EventLocationGPS'
  %br/
  = label :event, :EventLocationFriendly, 'Location '
  = text_field :event, :EventLocationFriendly
  %br/
  = label :event, :FromLocation, 'Meet at:'
  = text_field :event, 'FromLocation'
  %br/
  = label :event, :ToLocation, 'Destination'
  = text_field :event, :ToLocation
  %br/
  = label :event, :QuantityCanCarry, 'Can hold'
  = number_field :event, :QuantityCanCarry
  %br/
  = label :event, :OneWayTrip, 'One way trip'
  = select :event, :OneWayTrip, ['Yes','No']
  %br/
  = label :event, :EventBufferTime, 'Get here by'
  = text_field :event, 'EventBufferTime'
  %br/
  = label :event, :EventComments, 'Comment'
  = text_field :event, 'EventComments'
  %br/
  = submit_tag 'Submit'

app/views/events/show.html.haml
%div
.MoreAboutEvent
 %h2 Event # #{@event.id} Details
 %img{:src =>  asset_path("checkMark.png"), :width => "10%",:height => "5%", :float => "right"}/
 %br/
 %br/
 %b On : #{@event.EventDate} , you will travel from #{@event.FromLocation} to #{@event.ToLocation}  (#{@event.EventLocationFriendly})  
 %br/
 %ul
 %li Availability: #{@event.QuantityCanCarry}
 %li Going one way? #{@event.OneWayTrip}
 %li Arrive #{@event.EventBufferTime} min(s) prior
 %li  Meet driver @ coordinates#  : #{@event.EventLocationGPS}
 %h5 Owner Comments: #{@event.EventComments}
%br/
= link_to 'Back to Events', eventspage_path
%br/
- if user_signed_in?
 - if @event.user_id == current_user.id
  = link_to 'Edit Event Details', edit_event_path(@event)
  = link_to 'Delete Event', event_path(@event), :method => :delete
= submit_tag 'Join!'

app/views/layouts/_menu.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Ride Me", root_path, class: 'navbar-brand'
    #navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Events', 'events_path'
        - if current_user
          %li= link_to 'Edit Profile',edit_user_registration_path
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ride Me!!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    //%link{:href => "http://cdn.syncfusion.com/13.2.0.29/js/web/flat-azure/ej.web.all.min.css", :rel => "stylesheet"}/
    %script{:src => "https://code.jquery.com/jquery-1.10.2.min.js"}
    //%script{:src => "http://cdn.syncfusion.com/js/assets/external/jquery.easing.1.3.min.js"} 
    //%script{:src => "http://cdn.syncfusion.com/js/assets/external/jquery.globalize.min.js"}
    //%script{:src => "http://cdn.syncfusion.com/js/assets/external/jsrender.min.js"}
    //%script{:src => "http://cdn.syncfusion.com/13.2.0.29/js/web/ej.web.all.min.js"} 
    //%link{:href => "http://www.w3schools.com/lib/w3.css", :rel => "stylesheet"}/
    //%link{:href => "app/assets/stylesheets/mycss.css", :rel => "stylesheet"}/
    %link{:href => "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css", :rel => "stylesheet"}/
    %link{:href => "/resources/demos/style.css", :rel => "stylesheet"}/
    %script{:src => "https://code.jquery.com/jquery-1.12.4.js"}
    %script{:src => "https://code.jquery.com/ui/1.12.1/jquery-ui.js"}
  %body
  .nav.navbar-default
  
  .container
    .navbar-header
      = link_to "|||RideMe!|||", root_path, class:"navbar-brand"
      %img{:height => "50", :src => asset_path("my_tweet.png"), :width => "100"}
      
    %ul.nav.navbar-nav
      - if user_signed_in?
        %li= link_to "Home", homepage_path
        %li
        %li= link_to "Events", eventspage_path
        %li
        %li= link_to "My Profile", current_user
        %li
        %li= link_to "Logout", destroy_user_session_path, :method => :delete
        %br/
      - else
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Log In", new_user_session_path
  #main
    %p.notice= notice
    %p.alert= alert

    = yield

app/views/movies/AddCar.html.haml
%h2 Ride Me: Add your car

= form_tag movies_path, :method => :post do

  = label :movie, :CarMake, 'Make'
  = text_field :movie, :CarMake
  %br/
  = label :movie, :CarModel, 'Model'
  = text_field :movie, :CarModel
  %br/
  = label :movie, :CarYear, 'Year'
  = text_field :movie, :CarYear
  %br/
  = label :movie, :CarColor, 'Color'
  = text_field :movie, :CarColor
  %br/
  = label :movie, :CarLicense, 'Car License'
  = text_field :movie, :CarLicense
  %br/
  = label :movie, :CarLicenseState, 'Lic State'
  = text_field :movie, :CarLicenseState
  %br/
  = label :movie, :CarMPG, 'Car MPG'
  = text_field :movie, :CarMPG
  %br/
  = label :movie, :CarOwnerID, 'Your Owner ID'
  = text_field :movie, :CarOwnerID
 
  = submit_tag 'Save Changes'
  %br
  %br
  = link_to 'Cancel', movies_path

app/views/movies/CreateProfile.html.haml
%h2 Create New Movie

= form_tag movies_path, :method => :post do

  = label :movie, :title, 'The Movie Title'
  = text_field :movie, :title

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date
  %br/ 
  %br/ 

  = submit_tag 'Save Changes'
  %br
  %br
  = link_to 'Cancel', movies_path

app/views/movies/create.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 Saved  (I'm the create.html.haml page)

app/views/movies/edit.html.haml
%h2 Edit Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
  = label :movie, :release_date, 'Released On'
  = date_select( :movie, :release_date, start_year: 1930)
  
  = submit_tag 'Save Changes'
  %br
  %br
  = link_to 'Cancel', movies_path

app/views/movies/new.html.haml
%h2 Ride Me: Create your profile

= form_tag movies_path, :method => :post do

  = label :movie, :FirstName, 'First Name'
  = text_field :movie, :FirstName
  %br/
  = label :movie, :MiddleInitial, 'MI'
  = text_field :movie, :MiddleInitial
  %br/
  = label :movie, :LastName, 'Last Name'
  = text_field :movie, :LastName
  %br/
  = label :movie, :CarOwnerID, 'Choose Your Car'
  = text_field :movie, :CarOwnerID
  %br/
  = label :movie, :DateOfBirth, 'D.O.B'
  = text_field :movie, :DateOfBirth
  %br/
  = label :movie, :EmailAddress, 'Email'
  = text_field :movie, :EmailAddress
  %br/
  = label :movie, :PostalAddress, 'Address'
  = text_field :movie, :PostalAddress
  %br/
  = label :movie, :City, 'City'
  = text_field :movie, :City
  %br/
  = label :movie, :State, 'State'
  = text_field :movie, :State
  %br/
  = label :movie, :Zip, 'Zip'
  = text_field :movie, :Zip
  %br/
  = label :movie, :PhoneNumber, 'Phone'
  = text_field :movie, :PhoneNumber
  %br/
  = submit_tag 'Save Changes'
  %br
  %br
  = link_to 'Cancel', movies_path

app/views/movies/oops.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 Something went wrong.

= link_to 'Go back...', movie_path

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Back to movie list', movies_path
%br

= link_to 'Edit info', edit_movie_path(@movie)
%br
= link_to 'Back to movie list', movies_path

app/views/users/edit.html.haml
%h2
  Edit #{resource_name.to_s.humanize}
= form_for(resource, as: resource_name, url: edit_user_path(resource_name), html: { method: :put }) do |f|
  = devise_error_messages!
  %div
    = f.label :first_name
    %br/
    = f.text_field :first_name, autofocus: true
    %div
    = f.label :middle_name
    %br/
    = f.text_field :middle_name
  %div
    = f.label :date_of_birth
    %br/
    = f.date_select :date_of_birth
  %div
    = f.label :email
    %br/
    = f.email_field :email
  - if devise_mapping.confirmable? && resource.pending_reconfirmation?
    %div
      Currently waiting confirmation for: #{resource.unconfirmed_email}
  %div
    = f.label :password
    %i (leave blank if you don't want to change it)
    %br/
    = f.password_field :password, autocomplete: "off"
  %div
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation, autocomplete: "off"
  %div
    = f.label :current_password
    %i (we need your current password to confirm your changes)
    %br/
    = f.password_field :current_password, autocomplete: "off"
  %div= f.submit "Update"
%h3 Cancel my account
%p
  Unhappy? #{button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete}
= link_to "Back", :back

app/views/users/show.html.haml
%h2 Email ID: #{@user.email}
.row
  .col-md-4.col-md-offset-4.center
    = gravatar_for @user
    = link_to 'Edit Profile', edit_user_registration_path

%div{:align => "center"}
  = will_paginate @user_events
  
%h3 Events Added:

- @user_events.each do |event|
  .row
    .col-md-10.col-md-offset-1.col-xs-12
      = link_to event.EventDate, event_path(event)

%div{:align => "center"}
  = will_paginate @user_events